%-----------------------------------------------------------------------
% Job saved on 18-Jun-2013 20:54:00 by cfg_util (rev $Rev: 2911 $)
% spm SPM - SPM12b (5373)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.var_targets = {
                                                                                   './DWI/AP/0000.nii,1'
                                                                                   './DWI/AP/0001.nii,1'
                                                                                   };
%%
matlabbatch{1}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.sources = {
                                                                               './DWI/AP/0002.nii,1'
                                                                               './DWI/AP/0003.nii,1'
                                                                               './DWI/AP/0004.nii,1'
                                                                               './DWI/AP/0005.nii,1'
                                                                               './DWI/AP/0006.nii,1'
                                                                               './DWI/AP/0007.nii,1'
                                                                               './DWI/AP/0008.nii,1'
                                                                               './DWI/AP/0009.nii,1'
                                                                               './DWI/AP/0010.nii,1'
                                                                               './DWI/AP/0011.nii,1'
                                                                               './DWI/AP/0012.nii,1'
                                                                               './DWI/AP/0013.nii,1'
                                                                               './DWI/AP/0014.nii,1'
                                                                               './DWI/AP/0015.nii,1'
                                                                               './DWI/AP/0016.nii,1'
                                                                               './DWI/AP/0017.nii,1'
                                                                               './DWI/AP/0018.nii,1'
                                                                               './DWI/AP/0019.nii,1'
                                                                               './DWI/AP/0020.nii,1'
                                                                               './DWI/AP/0021.nii,1'
                                                                               './DWI/AP/0022.nii,1'
                                                                               './DWI/AP/0023.nii,1'
                                                                               './DWI/AP/0024.nii,1'
                                                                               './DWI/AP/0025.nii,1'
                                                                               './DWI/AP/0026.nii,1'
                                                                               './DWI/AP/0027.nii,1'
                                                                               './DWI/AP/0028.nii,1'
                                                                               './DWI/AP/0029.nii,1'
                                                                               './DWI/AP/0030.nii,1'
                                                                               './DWI/AP/0031.nii,1'
                                                                               './DWI/AP/0032.nii,1'
                                                                               './DWI/AP/0033.nii,1'
                                                                               './DWI/AP/0034.nii,1'
                                                                               './DWI/AP/0035.nii,1'
                                                                               './DWI/AP/0036.nii,1'
                                                                               './DWI/AP/0037.nii,1'
                                                                               './DWI/AP/0038.nii,1'
                                                                               './DWI/AP/0039.nii,1'
                                                                               './DWI/AP/0040.nii,1'
                                                                               './DWI/AP/0041.nii,1'
                                                                               './DWI/AP/0042.nii,1'
                                                                               './DWI/AP/0043.nii,1'
                                                                               './DWI/AP/0044.nii,1'
                                                                               './DWI/AP/0045.nii,1'
                                                                               './DWI/AP/0046.nii,1'
                                                                               './DWI/AP/0047.nii,1'
                                                                               './DWI/AP/0048.nii,1'
                                                                               './DWI/AP/0049.nii,1'
                                                                               './DWI/AP/0050.nii,1'
                                                                               './DWI/AP/0051.nii,1'
                                                                               './DWI/AP/0052.nii,1'
                                                                               './DWI/AP/0053.nii,1'
                                                                               './DWI/AP/0054.nii,1'
                                                                               './DWI/AP/0055.nii,1'
                                                                               './DWI/AP/0056.nii,1'
                                                                               './DWI/AP/0057.nii,1'
                                                                               './DWI/AP/0058.nii,1'
                                                                               './DWI/AP/0059.nii,1'
                                                                               './DWI/AP/0060.nii,1'
                                                                               './DWI/AP/0061.nii,1'
                                                                               './DWI/AP/0062.nii,1'
                                                                               './DWI/AP/0063.nii,1'
                                                                               './DWI/AP/0064.nii,1'
                                                                               './DWI/AP/0065.nii,1'
                                                                               './DWI/AP/0066.nii,1'
                                                                               };
%%
matlabbatch{1}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.bval_target = [0 1000];
matlabbatch{1}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.bval_source = [1000 1000 1000 1000 1000 1000 1000 1000 1000 0 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 0 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 0 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 0 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 0 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 0];
matlabbatch{1}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.freeze = [1 1 1 1 1 1 0 1 0 1 1 0];
matlabbatch{1}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.write = 1;
matlabbatch{1}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.disp_ECMO = 1;
matlabbatch{2}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.var_targets = {
                                                                                   './DWI/AP/0000.nii,1'
                                                                                   './DWI/AP/0001.nii,1'
                                                                                   };
matlabbatch{2}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.sources = {
                                                                               './DWI/PA/0000.nii,1'
                                                                               './DWI/PA/0001.nii,1'
                                                                               };
matlabbatch{2}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.bval_target = [0 1000];
matlabbatch{2}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.bval_source = [0 1000];
matlabbatch{2}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.freeze = [1 1 1 1 1 1 0 1 0 1 1 0];
matlabbatch{2}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.write = 1;
matlabbatch{2}.spm.tools.dti.prepro_choice.ecmo_choice.ec_mo_vartar.disp_ECMO = 0;
matlabbatch{3}.cfg_basicio.file_dir.dir_ops.cfg_mkdir.parent = {'./DWI/AP'};
matlabbatch{3}.cfg_basicio.file_dir.dir_ops.cfg_mkdir.name = 'MovementCorrected';
matlabbatch{4}.cfg_basicio.file_dir.dir_ops.cfg_mkdir.parent = {'./DWI/PA'};
matlabbatch{4}.cfg_basicio.file_dir.dir_ops.cfg_mkdir.name = 'MovementCorrected';
%%
matlabbatch{5}.cfg_basicio.file_dir.file_ops.file_move.files = {
                                                                './DWI/AP/EC_mut_p2_0002.eps'
                                                                './DWI/AP/MO_mut_p2_0002.eps'
                                                                './DWI/AP/mut_p2_0002.mat'
                                                                './DWI/AP/mut_p2_0003.mat'
                                                                './DWI/AP/mut_p2_0004.mat'
                                                                './DWI/AP/mut_p2_0005.mat'
                                                                './DWI/AP/mut_p2_0006.mat'
                                                                './DWI/AP/mut_p2_0007.mat'
                                                                './DWI/AP/mut_p2_0008.mat'
                                                                './DWI/AP/mut_p2_0009.mat'
                                                                './DWI/AP/mut_p2_0010.mat'
                                                                './DWI/AP/mut_p2_0011.mat'
                                                                './DWI/AP/mut_p2_0012.mat'
                                                                './DWI/AP/mut_p2_0013.mat'
                                                                './DWI/AP/mut_p2_0014.mat'
                                                                './DWI/AP/mut_p2_0015.mat'
                                                                './DWI/AP/mut_p2_0016.mat'
                                                                './DWI/AP/mut_p2_0017.mat'
                                                                './DWI/AP/mut_p2_0018.mat'
                                                                './DWI/AP/mut_p2_0019.mat'
                                                                './DWI/AP/mut_p2_0020.mat'
                                                                './DWI/AP/mut_p2_0021.mat'
                                                                './DWI/AP/mut_p2_0022.mat'
                                                                './DWI/AP/mut_p2_0023.mat'
                                                                './DWI/AP/mut_p2_0024.mat'
                                                                './DWI/AP/mut_p2_0025.mat'
                                                                './DWI/AP/mut_p2_0026.mat'
                                                                './DWI/AP/mut_p2_0027.mat'
                                                                './DWI/AP/mut_p2_0028.mat'
                                                                './DWI/AP/mut_p2_0029.mat'
                                                                './DWI/AP/mut_p2_0030.mat'
                                                                './DWI/AP/mut_p2_0031.mat'
                                                                './DWI/AP/mut_p2_0032.mat'
                                                                './DWI/AP/mut_p2_0033.mat'
                                                                './DWI/AP/mut_p2_0034.mat'
                                                                './DWI/AP/mut_p2_0035.mat'
                                                                './DWI/AP/mut_p2_0036.mat'
                                                                './DWI/AP/mut_p2_0037.mat'
                                                                './DWI/AP/mut_p2_0038.mat'
                                                                './DWI/AP/mut_p2_0039.mat'
                                                                './DWI/AP/mut_p2_0040.mat'
                                                                './DWI/AP/mut_p2_0041.mat'
                                                                './DWI/AP/mut_p2_0042.mat'
                                                                './DWI/AP/mut_p2_0043.mat'
                                                                './DWI/AP/mut_p2_0044.mat'
                                                                './DWI/AP/mut_p2_0045.mat'
                                                                './DWI/AP/mut_p2_0046.mat'
                                                                './DWI/AP/mut_p2_0047.mat'
                                                                './DWI/AP/mut_p2_0048.mat'
                                                                './DWI/AP/mut_p2_0049.mat'
                                                                './DWI/AP/mut_p2_0050.mat'
                                                                './DWI/AP/mut_p2_0051.mat'
                                                                './DWI/AP/mut_p2_0052.mat'
                                                                './DWI/AP/mut_p2_0053.mat'
                                                                './DWI/AP/mut_p2_0054.mat'
                                                                './DWI/AP/mut_p2_0055.mat'
                                                                './DWI/AP/mut_p2_0056.mat'
                                                                './DWI/AP/mut_p2_0057.mat'
                                                                './DWI/AP/mut_p2_0058.mat'
                                                                './DWI/AP/mut_p2_0059.mat'
                                                                './DWI/AP/mut_p2_0060.mat'
                                                                './DWI/AP/mut_p2_0061.mat'
                                                                './DWI/AP/mut_p2_0062.mat'
                                                                './DWI/AP/mut_p2_0063.mat'
                                                                './DWI/AP/mut_p2_0064.mat'
                                                                './DWI/AP/mut_p2_0065.mat'
                                                                './DWI/AP/mut_p2_0066.mat'
                                                                './DWI/AP/r0002.nii'
                                                                './DWI/AP/r0003.nii'
                                                                './DWI/AP/r0004.nii'
                                                                './DWI/AP/r0005.nii'
                                                                './DWI/AP/r0006.nii'
                                                                './DWI/AP/r0007.nii'
                                                                './DWI/AP/r0008.nii'
                                                                './DWI/AP/r0009.nii'
                                                                './DWI/AP/r0010.nii'
                                                                './DWI/AP/r0011.nii'
                                                                './DWI/AP/r0012.nii'
                                                                './DWI/AP/r0013.nii'
                                                                './DWI/AP/r0014.nii'
                                                                './DWI/AP/r0015.nii'
                                                                './DWI/AP/r0016.nii'
                                                                './DWI/AP/r0017.nii'
                                                                './DWI/AP/r0018.nii'
                                                                './DWI/AP/r0019.nii'
                                                                './DWI/AP/r0020.nii'
                                                                './DWI/AP/r0021.nii'
                                                                './DWI/AP/r0022.nii'
                                                                './DWI/AP/r0023.nii'
                                                                './DWI/AP/r0024.nii'
                                                                './DWI/AP/r0025.nii'
                                                                './DWI/AP/r0026.nii'
                                                                './DWI/AP/r0027.nii'
                                                                './DWI/AP/r0028.nii'
                                                                './DWI/AP/r0029.nii'
                                                                './DWI/AP/r0030.nii'
                                                                './DWI/AP/r0031.nii'
                                                                './DWI/AP/r0032.nii'
                                                                './DWI/AP/r0033.nii'
                                                                './DWI/AP/r0034.nii'
                                                                './DWI/AP/r0035.nii'
                                                                './DWI/AP/r0036.nii'
                                                                './DWI/AP/r0037.nii'
                                                                './DWI/AP/r0038.nii'
                                                                './DWI/AP/r0039.nii'
                                                                './DWI/AP/r0040.nii'
                                                                './DWI/AP/r0041.nii'
                                                                './DWI/AP/r0042.nii'
                                                                './DWI/AP/r0043.nii'
                                                                './DWI/AP/r0044.nii'
                                                                './DWI/AP/r0045.nii'
                                                                './DWI/AP/r0046.nii'
                                                                './DWI/AP/r0047.nii'
                                                                './DWI/AP/r0048.nii'
                                                                './DWI/AP/r0049.nii'
                                                                './DWI/AP/r0050.nii'
                                                                './DWI/AP/r0051.nii'
                                                                './DWI/AP/r0052.nii'
                                                                './DWI/AP/r0053.nii'
                                                                './DWI/AP/r0054.nii'
                                                                './DWI/AP/r0055.nii'
                                                                './DWI/AP/r0056.nii'
                                                                './DWI/AP/r0057.nii'
                                                                './DWI/AP/r0058.nii'
                                                                './DWI/AP/r0059.nii'
                                                                './DWI/AP/r0060.nii'
                                                                './DWI/AP/r0061.nii'
                                                                './DWI/AP/r0062.nii'
                                                                './DWI/AP/r0063.nii'
                                                                './DWI/AP/r0064.nii'
                                                                './DWI/AP/r0065.nii'
                                                                './DWI/AP/r0066.nii'
                                                                };
%%
matlabbatch{5}.cfg_basicio.file_dir.file_ops.file_move.action.moveto = {'./DWI/AP/MovementCorrected'};
matlabbatch{6}.cfg_basicio.file_dir.file_ops.file_move.files = {
                                                                './DWI/PA/mut_p2_0000.mat'
                                                                './DWI/PA/mut_p2_0001.mat'
                                                                './DWI/PA/r0000.nii'
                                                                './DWI/PA/r0001.nii'
                                                                };
matlabbatch{6}.cfg_basicio.file_dir.file_ops.file_move.action.moveto = {'./DWI/PA/MovementCorrected'};
